[server]
# Configurações para melhor experiência mobile
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
# Configurações do navegador para mobile
gatherUsageStats = false

[client]
# Configurações do cliente
showErrorDetails = true
toolbarMode = "minimal"
