[gcp_service_account]
type = "service_account"
project_id = "uplifted-water-472222-k7"
private_key_id = "df29e61eb2d219de56151d1568a3078c06bc5ad1"
private_key = '''-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCk0KQifGi1zaBW
rwzzO+LkJg77H9HRmx0QZ7/x9z77V/AMlc0AUAIyw68XUqwqNwp3mJxCgwZouxzM
CVZFo9ovKyOrz9iPTRBGGl/varF6zq0HU3SE3eZkYPwBuLGdpNGs9ieLSoZYB6LQ
QQs4VW4MX/D4Enu7IgF0CSjuHZJjdMLUoIbF+XS2GRRT2CVy/SfbaPd7udA+BIyu
lfJfASjDX2qClW8qIWNY2LgjhLH8EJ37IU+4JvYriUjBMy+AXglg2LHZ1zLwzc/9
LLoUxLROZgA/ougdeXC6qUaDmfgg2kRvebSYyU0JDW/fvjf5+L05fTwHqtK3o7fS
gGWOinjvAgMBAAECggEAP/6/bKCP69++3Um1JpDfRaU9debiCphHDcKrNiHBs8hu
bgSQiAmJAPsYdl7keLPMfamlKvJDP9E/mj4Z4IqBwoTmoeTfeqz6n63ICGeOKFgt
nuUV/XcPnnJxH3cdAOCzyOU2PBzfVuEKmxmQrHiGVzHpIT5qlroDCvbJ80RBsce8Z
3wckyui23I6e+0uH+e1977fefVt7fYDFC38m+W8ws8lKqjb4G6SM38KuNISLbk6w
pch69RFmQQ6BDjNNX4hikT7f/fV0+5ICkeTMul1NM+0X24BrYVLZEK1p3fuuQf28
aLuxsIukxzcu96TfRo0fvdpJNvm+VYdwBF6NquGeYQKBgQDOOO2k0LMLkAGh0aeq
W8iOa1UCYWRI7X/Do21Af/qD6d/5I1txvsMePSKqOMKbyIWLh3556QjvOVcEw6lN
1/jqclME5HjoPkrS/mpR/SQ6wRhMM3nbycTO9gNTpoJDoO04Kiu39wm26ziHOi6m
uK0lo8YM2ZtKWwTT/YRzBT8InwKBgQDMmQhdhq3SMaLBJj6nHoO0GFNQYtuZ9MH3
KqUp+7IWU/rbHnFobDyiPePO42qx50Qjeo5gIVhc0JFaToTdoqnFJhmTwnCATrSL
A9DgeuuEg+TzDE73SKWwT0/rSM0EK0zd2TzcOcsz3Fc0pxdwtM/KDoRrlApjifvr
po+entSdsQKBgQCPJptoXmr7KsLHRpbhvgbRPhZrqZmIujyHXMm5DV2j9lRASFfw
9F/TfNK0YOROaXqyaaLVE3vdO+t45i1/WN10OVoBumtno94i6vJ46YUdt+6a7ty3
Qi95DvMuPRaNxYcGBtgEQtsee9fonu3FU8r1puMTBncyvU3zrjcj9M9VtwKBgBJt
qko6SkfHfsBlAHmvDu/WzRJNhTgtypbHuY65hAXs1IiOCmr8bM20Q2OsKj0R9po3
fMF932akxqLata786su+LcmYVufHrw1ib5r4l2QdOS8HKcmuOnZR/oHT0duRRuAo
pAm2Du6B5zzv2/Wj459whU7nS7RBhnZoT0FbTw1RAoGBAJ0b8UrNj3TnF3MFdH3Z
02PqqaJdCJ/LNYdzAQ6IO8sB3PgsUaze5SI27cH4A6/O2qhZ3VyAZaKcpQ+kvATn
Y0dccmbqfeDNRnAlX9vbA5AFzLwijhwNq/sKUirvOhr8TikNRFiTkI+v0tebXGq3
LS7uV72pKMuOjH15RVsBJDhA
-----END PRIVATE KEY-----'''
client_email = "ghuntter@uplifted-water-472222-k7.iam.gserviceaccount.com"
client_id = "106734438352197864893"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/ghuntter%40uplifted-water-472222-k7.iam.gserviceaccount.com"
universe_domain = "googleapis.com"