# secrets_example.toml - Exemplo de configuração para o Streamlit
# Copie este arquivo para secrets.toml e preencha com suas credenciais reais

[gcp_service_account]
type = "service_account"
project_id = "seu-projeto-id"
private_key_id = "sua-chave-privada-id"
# IMPORTANTE: Cole a chave privada EXATAMENTE como vem do JSON, com quebras de linha preservadas
private_key = '''-----BEGIN PRIVATE KEY-----
SUA_CHAVE_PRIVADA_AQUI_COM_QUEBRAS_DE_LINHA_PRESERVADAS
-----END PRIVATE KEY-----'''
client_email = "sua-service-account@seu-projeto.iam.gserviceaccount.com"
client_id = "seu-client-id"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/sua-service-account%40seu-projeto.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
