[gcp_service_account]
type = "service_account"
project_id = "uplifted-water-472222-k7"
private_key_id = "COLE_AQUI_O_private_key_id"
# IMPORTANTE: Cole a chave privada COMPLETA do seu arquivo JSON de credenciais
private_key = '''-----BEGIN PRIVATE KEY-----
COLE_AQUI_SUA_CHAVE_PRIVADA_COMPLETA_DO_ARQUIVO_JSON
-----END PRIVATE KEY-----'''
client_email = "colab-27@uplifted-water-472222-k7.iam.gserviceaccount.com"
client_id = "110235144704036821022"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/colab-27%40uplifted-water-472222-k7.iam.gserviceaccount.com"
universe_domain = "googleapis.com"